openapi: 3.0.0
info:
  title: Example Item Management API
  description: "API for managing items"
  version: 1.0.0
servers:
  - url: https://example.com/api
    description: "Example API server"
paths:
  /items:
    get:
      summary: Get all items
      operationId: getItems
      responses:
        "200":
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      summary: Create a new item
      operationId: createItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemInput"
      responses:
        "201":
          description: The created item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
  /items/{id}:
    get:
      summary: Get a specific item
      operationId: getItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Details of the specified item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
    put:
      summary: Update a specific item
      operationId: updateItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemInput"
      responses:
        "200":
          description: The updated item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
    delete:
      summary: Delete a specific item
      operationId: deleteItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Item deleted successfully
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        value:
          type: integer
      example:
        id: 1
        name: "Sample Item"
        value: 42
    ItemInput:
      type: object
      properties:
        name:
          type: string
        value:
          type: integer
      required:
        - name
        - value

